name: ci-test-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.4
      - run: go test
      - run: go run math.go
