name: ci-test-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker builds
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: DanielLevi22/CI:latest
